AcmeUserBundle:
    resource: "@AcmeUserBundle/Controller/"
    type:     annotation
    prefix:   /

SupplierBundle:
    resource: "@SupplierBundle/Controller/"
    type:     annotation
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal

adminboard:
      pattern: /adminboard/{name}
      defaults: {_controller: AcmeAdminBoardBundle:AdminBoard:index}
