security:
    encoders:
        Acme\UserBundle\Entity\User: plaintext

    role_hierarchy:
        ROLE_RESTAURANT_ADMIN: [ROLE_RESTAURANT_ADMIN]
        ROLE_ORDER_MANAGER:    [ROLE_RESTAURANT_ADMIN, ROLE_ORDER_MANAGER]
        ROLE_COMPANY_ADMIN:    [ROLE_COMPANY_ADMIN]
        ROLE_ADMIN:            [ROLE_ADMIN]
        ROLE_SUPER_ADMIN:      [ROLE_RESTAURANT_ADMIN, ROLE_ORDER_MANAGER, ROLE_COMPANY_ADMIN, ROLE_ADMIN, ROLE_SUPER_ADMIN]
        

    providers:
        main:
            entity: { class: AcmeUserBundle:User, property: username}

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/login$
            security: false

        secured_area:
            form_login: ~
            logout: ~
            anonymous: ~
            http_basic:
                realm: "Secured Demo Area"

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #- { path: ^/_internal, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
